server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ml/latest {
        proxy_pass http://host.docker.internal:8001/latest;
    }
}
